### ISSUE TITLE
I try ComfyUI Alimama on flux dev and got an error

### ISSUE THREAD

**Issue by ShmuelRonen** [zhiselfly/ComfyUI-Alimama-ControlNet-compatible#4]
I use the controlnet model: **FLUX.1-dev-Controlnet-Inpainting-Alpha.safetensors** and try to execute and got this error: TypeError: MMDiT.__init__() got an unexpected keyword argument 'image_model'

![error](https://github.com/user-attachments/assets/e630bae6-e3f6-4271-992a-e75a01fe7290)

________________

# ComfyUI Error Report
## Error Details
- **Node Type:** SD3AlimamaInpaintControlNetLoader
- **Exception Type:** TypeError
- **Exception Message:** MMDiT.__init__() got an unexpected keyword argument 'image_model'
## Stack Trace
```
  File "/home/sam/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/sam/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/sam/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/home/sam/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/home/sam/ComfyUI/custom_nodes/ComfyUI-Alimama-ControlNet-compatible/nodes.py", line 64, in load_controlnet
    controlnet = load_controlnet_mmdit(controlnet_data)

  File "/home/sam/ComfyUI/custom_nodes/ComfyUI-Alimama-ControlNet-compatible/nodes.py", line 39, in load_controlnet_mmdit
    control_model = AlimamaControlNet(num_blocks=num_blocks, operations=operations, device=load_device, dtype=unet_dtype, extra_cond_channels=extra_cond_channels, **model_config.unet_config)

  File "/home/sam/ComfyUI/custom_nodes/ComfyUI-Alimama-ControlNet-compatible/model/alimama_controlnet.py", line 15, in __init__
    super(comfy.cldm.mmdit.ControlNet, self).__init__(dtype=dtype, device=device, operations=operations, final_layer=False, num_blocks=num_blocks, **kwargs)

```
## System Information
- **ComfyUI Version:** v0.2.2-50-g0bfc7cc
- **Arguments:** main.py --front-end-version Comfy-Org/ComfyUI_frontend@latest --fast --reserve-vram 2
- **OS:** posix
- **Python Version:** 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25769279488
  - **VRAM Free:** 24438112256
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

**Comment by ShmuelRonen** [comment]
Ok... I replace the Alimama ControlNet loader with the regular loader and this fix the issue for me.

**Comment by zhiselfly** [comment]
This plugin is only compatible with SD3 using Alimama's ControlNet-inpainting model, and it is just a demo. I have not adapted it for models other than SD3. Moreover, the official ComfyUI has already provided support for Alimama's model earlier, so please use the official version.
